DBADM_Activos/Controllers/TipoEdificioController.cs
using DBADM_Activos.Models;
using DBADM_Activos.ServiceReference1;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DBADM_Activos.Controllers
{
    public class TipoEdificioController : Controller
    {
        Service1Client client = new Service1Client();

        // GET: TipoEdificio
        public ActionResult Index()
        {
            var list = client.listTipoEdiConstru();

            return View(list);
        }

        public ActionResult createTipoEdi()
        {
            return View();
        }

        [HttpPost]
        public ActionResult createTipoEdi(TipoEdificioConstruCLS edi)
        {
            client.createTipoEdiConstru(edi.NombreTipoEdificio, edi.DescripcionTipo);

            return RedirectToAction("Index");
        }

        public ActionResult updateTipoEdi(int id)
        {
            TipoEdificioConstruCLS tedi = new TipoEdificioConstruCLS();

            var item = client.detailTipoEdiConstru(id);

            tedi.IdTipoEdificioConstruido = item.IdTipoEdificioConstruido;
            tedi.NombreTipoEdificio = item.NombreTipoEdificio;
            tedi.DescripcionTipo = item.DescripcionTipo;

            return View(tedi);
        }

        [HttpPost]
        public ActionResult updateTipoEdi(TipoEdificioConstruCLS edi)
        {
            int st = (int)client.updateTipoEdiConstru(edi.IdTipoEdificioConstruido, edi.NombreTipoEdificio, edi.DescripcionTipo).estado;

            return RedirectToAction("Index");
        }

        public ActionResult deleteTipoEdi(int id)
        {
            TipoEdificioConstruCLS tedi = new TipoEdificioConstruCLS();

            var item = client.detailTipoEdiConstru(id);

            tedi.IdTipoEdificioConstruido = item.IdTipoEdificioConstruido;
            tedi.NombreTipoEdificio = item.NombreTipoEdificio;
            tedi.DescripcionTipo = item.DescripcionTipo;

            return View(tedi);
        }

        [HttpPost]
        public ActionResult deleteTipoEdi(TipoEdificioConstruCLS edi)
        {
            int st = (int)client.deleteTipoEdiConstru(edi.IdTipoEdificioConstruido).estado;

            return RedirectToAction("Index");
        }

        public ActionResult detailTipoEdi(int id)
        {
            TipoEdificioConstruCLS tedi = new TipoEdificioConstruCLS();

            var item = client.detailTipoEdiConstru(id);

            tedi.IdTipoEdificioConstruido = item.IdTipoEdificioConstruido;
            tedi.NombreTipoEdificio = item.NombreTipoEdificio;
            tedi.DescripcionTipo = item.DescripcionTipo;

            return View(tedi);
        }
    }
}

DBADM_Activos/Views/TipoEdificio/Index.cshtml
@model IEnumerable<DBADM_Activos.ServiceReference1.SP_TipoEdificioConstru_toList_Result>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Crear nuevo", "createTipoEdi", "TipoEdificio")
</p>
<table class="table table-hover table-bordered" style="width:100%">
    <thead class="thead-dark">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DescripcionTipo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdTipoEdificioConstruido)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NombreTipoEdificio)
            </th>
            <th></th>
        </tr>
    </thead>
@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.DescripcionTipo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IdTipoEdificioConstruido)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NombreTipoEdificio)
        </td>
        <td>
            @Html.ActionLink("Edit", "updateTipoEdi", "TipoEdificio", new { id = item.IdTipoEdificioConstruido }, null) |
            @Html.ActionLink("Details", "detailTipoEdi", "TipoEdificio", new { id = item.IdTipoEdificioConstruido }, null) |
            @Html.ActionLink("Delete", "deleteTipoEdi", "TipoEdificio", new { id = item.IdTipoEdificioConstruido }, null)
        </td>
    </tr>
}

</table>

DBADM_Activos/Views/TipoEdificio/createTipoEdi.cshtml
@model DBADM_Activos.Models.TipoEdificioConstruCLS

@{
    ViewBag.Title = "createTipoEdi";
}

<h2>createTipoEdi</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TipoEdificioConstruCLS</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.IdTipoEdificioConstruido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdTipoEdificioConstruido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdTipoEdificioConstruido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NombreTipoEdificio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NombreTipoEdificio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NombreTipoEdificio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DescripcionTipo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DescripcionTipo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DescripcionTipo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

DBADM_Activos/Views/TipoEdificio/deleteTipoEdi.cshtml
@model DBADM_Activos.Models.TipoEdificioConstruCLS

@{
    ViewBag.Title = "deleteTipoEdi";
}

<h2>deleteTipoEdi</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TipoEdificioConstruCLS</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.IdTipoEdificioConstruido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdTipoEdificioConstruido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdTipoEdificioConstruido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NombreTipoEdificio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NombreTipoEdificio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NombreTipoEdificio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DescripcionTipo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DescripcionTipo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DescripcionTipo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

DBADM_Activos/Views/TipoEdificio/detailTipoEdi.cshtml
@model DBADM_Activos.Models.TipoEdificioConstruCLS

@{
    ViewBag.Title = "detailTipoEdi";
}

<h2>detailTipoEdi</h2>

<div>
    <h4>TipoEdificioConstruCLS</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IdTipoEdificioConstruido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdTipoEdificioConstruido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NombreTipoEdificio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NombreTipoEdificio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DescripcionTipo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DescripcionTipo)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DBADM_Activos/Views/TipoEdificio/updateTipoEdi.cshtml
@model DBADM_Activos.Models.TipoEdificioConstruCLS

@{
    ViewBag.Title = "updateTipoEdi";
}

<h2>updateTipoEdi</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TipoEdificioConstruCLS</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.IdTipoEdificioConstruido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdTipoEdificioConstruido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdTipoEdificioConstruido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NombreTipoEdificio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NombreTipoEdificio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NombreTipoEdificio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DescripcionTipo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DescripcionTipo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DescripcionTipo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>