DBADM_Activos/Controllers/SectoresController.cs
using DBADM_Activos.Models;
using DBADM_Activos.ServiceReference1;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DBADM_Activos.Controllers
{
    public class SectoresController : Controller
    {
        Service1Client client = new Service1Client();

        // GET: Sectores
        public ActionResult Index()
        {
            var list = client.listSector();

            return View(list);
        }

        public ActionResult createSector()
        { 
            return View();
        }

        [HttpPost]
        public ActionResult createSector(SectoresCLS sec)
        {
            client.createSector(sec.IdSector, sec.DescripcionSector);

            return RedirectToAction("Index");
        }

        public ActionResult updateSector(string id)
        {
            SectoresCLS sect = new SectoresCLS();

            var item = client.detailSector(id);

            sect.IdSector = item.IdSector;
            sect.DescripcionSector = item.DescripcionSector;

            return View(sect);
        }

        [HttpPost]
        public ActionResult updateSector(SectoresCLS sec)
        {
            int st = (int)client.updateSector(sec.IdSector, sec.DescripcionSector, sec.NewIdSector).estado;

            return RedirectToAction("Index");
        }

        public ActionResult deleteSector(string id)
        {
            SectoresCLS sect = new SectoresCLS();

            var item = client.detailSector(id);

            sect.IdSector = item.IdSector;
            sect.DescripcionSector = item.DescripcionSector;

            return View(sect);
        }

        [HttpPost]
        public ActionResult deleteSector(SectoresCLS sec)
        {
            int st = (int)client.deleteSector(sec.IdSector).estado;

            return RedirectToAction("Index");
        }

        public ActionResult detailSector(string id)
        {
            SectoresCLS sect = new SectoresCLS();

            var item = client.detailSector(id);

            sect.IdSector = item.IdSector;
            sect.DescripcionSector = item.DescripcionSector;

            return View(sect);
        }
    }
}

DBADM_Activos/Views/Sectores/Index.cshtml
@model IEnumerable<DBADM_Activos.ServiceReference1.SP_Sectores_toList_Result>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Crear nuevo", "createSector", "Sectores")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.DescripcionSector)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IdSector)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.DescripcionSector)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IdSector)
        </td>
        <td>
            @Html.ActionLink("Edit", "editSector", new { id = item.IdSector }, null) |
            @Html.ActionLink("Details", "detailSector", new { id = item.IdSector }, null) |
            @Html.ActionLink("Delete", "deleteSector", new { id = item.IdSector }, null)
        </td>
    </tr>
}

</table>

DBADM_Activos/Views/Sectores/createSector.cshtml
@model DBADM_Activos.Models.SectoresCLS

@{
    ViewBag.Title = "createSector";
}

<h2>createSector</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SectoresCLS</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.IdSector, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdSector, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdSector, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DescripcionSector, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DescripcionSector, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DescripcionSector, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NewIdSector, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NewIdSector, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NewIdSector, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

DBADM_Activos/Views/Sectores/deleteSector.cshtml
@model DBADM_Activos.Models.SectoresCLS

@{
    ViewBag.Title = "deleteSector";
}

<h2>deleteSector</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SectoresCLS</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.IdSector, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdSector, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdSector, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DescripcionSector, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DescripcionSector, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DescripcionSector, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NewIdSector, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NewIdSector, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NewIdSector, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

DBADM_Activos/Views/Sectores/detailSector.cshtml
@model DBADM_Activos.Models.SectoresCLS

@{
    ViewBag.Title = "detailSector";
}

<h2>detailSector</h2>

<div>
    <h4>SectoresCLS</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IdSector)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdSector)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DescripcionSector)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DescripcionSector)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NewIdSector)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NewIdSector)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DBADM_Activos/Views/Sectores/updateSector.cshtml
@model DBADM_Activos.Models.SectoresCLS

@{
    ViewBag.Title = "updateSector";
}

<h2>updateSector</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SectoresCLS</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.IdSector, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdSector, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdSector, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DescripcionSector, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DescripcionSector, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DescripcionSector, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NewIdSector, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NewIdSector, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NewIdSector, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>